tag_prefix = "v"
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []

[commit_types]

[changelog]
authors = [{ username = "GrayJack", signature = "Eric Shimizu Karbstein" }]
path = "CHANGELOG.md"
template = ".changelog_template"

[bump_profiles]
