name: Check and Test

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.62.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Cache cargo output
      uses: Swatinem/rust-cache@v1
    - name: Check
      run: cargo check --workplace
    - name: Check and Run tests
      run: cargo test --workplace

  build-macos:
    name: MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [1.62.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Cache cargo output
      uses: Swatinem/rust-cache@v1
    - name: Check
      run: cargo check
    - name: Check and Run tests
      run: cargo test

  build-windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust: [1.62.0, stable, beta, nightly]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Cache cargo output
      uses: Swatinem/rust-cache@v1
    - name: Check
      run: cargo check
    - name: Check and Run tests
      run: cargo test
